disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
line_length:
  warning: 120
  error: 200
  ignores_comments: true
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 300
  error: 500
function_body_length:
  warning: 50
  error: 100
identifier_name:
  min_length: 2
  max_length: 50
